### ISSUE TITLE
Not wrking?

### ISSUE THREAD

**Issue by sergey-zero** [luk1337/vapor-report#1]
> [INFO] Plugin "console-logger" has been loaded successfully.
> [INFO] Plugin "stdin-steamguard" has been loaded successfully.
> [INFO] Plugin "fs" has been loaded successfully.
> [INFO] Plugin "vapor-report" has been loaded successfully.
> [INFO] Connecting to Steam network.
> [INFO] Connected to Steam network. Logging in...
> [INFO] accforoverwatchban_0005 logged in successfully.
> [INFO] Received new Steam server list.
> [INFO] Received new SteamGuard sentry file.
> [INFO] Received new web cookies.

and nothing .....

**Comment by luk1337** [comment]
It works here
>luk@kremowka:~/vapor-report$ ./report.sh 765611980272xxxxx
base_gcmessages.proto
cstrike15_gcmessages.proto
engine_gcmessages.proto
gcsdk_gcmessages.proto
protos.js
steammessages.proto
updater.js
[INFO] Plugin "console-logger" has been loaded successfully.
[INFO] Plugin "stdin-steamguard" has been loaded successfully.
[INFO] Plugin "fs" has been loaded successfully.
[INFO] Plugin "vapor-report" has been loaded successfully.
[INFO] Connecting to Steam network.
[INFO] Connected to Steam network. Logging in...
[INFO] xxxxx logged in successfully.
[INFO] Received new Steam server list.
[INFO] Received new web cookies.
[INFO] Trying to report the user!
[INFO] MM Client Hello sent!
[INFO] MM Client Hello sent!
[INFO] Report with confirmation ID: 3151936184100323462 sent!
[INFO] Disconnecting from Steam network.

**Comment by luk1337** [comment]
Do you have CS:GO on this account?

**Comment by sergey-zero** [comment]
no

**Comment by luk1337** [comment]
Ugh, you need to have CS:GO. I guess I'll make it fail if there's no steamGameCoordinator.

**Comment by sergey-zero** [comment]
Ok, srry

**Comment by luk1337** [comment]
https://github.com/luk1337/vapor-report/commit/6163caff27288172ea5ccf91b944d4b49ddd16b5
