### ISSUE TITLE
Stays at Connecting to Steam network

### ISSUE THREAD

**Issue by UHaweq12** [luk1337/vapor-report#21]
Console output: [INFO] Plugin "console-logger" has been loaded successfully.
[INFO] Plugin "fs" has been loaded successfully.
[INFO] Plugin "stdin-steamguard" has been loaded successfully.
[INFO] Plugin "vapor-commend" has been loaded successfully.
[INFO] Connecting to Steam network.

**Comment by luk1337** [comment]
reportbotting is dead but if you really insist on making this thing work, just update your ./node_modules/steam/lib/servers.js with https://gist.github.com/1acf2cbf7735c8d2adb400762f00bd84

**Comment by UHaweq12** [comment]
"[INFO] Plugin "vapor-commend" has been loaded successfully."
just want the commend bot but thank you ^^
